Renamed file variables

diff --git a/bing-ip2hosts b/bing-ip2hosts
--- a/bing-ip2hosts
+++ b/bing-ip2hosts
@@ -50,7 +50,7 @@ function ctrl_c() {
 
   # clean up tmp files
   if [[ $DEBUG == 0 ]]; then
-    rm -f "$out"
+    rm -f "$f_scraped_html"
   fi
 
   show_hosts
@@ -125,13 +125,13 @@ function show_hosts() {
     echo -e "$N"
   fi
 
-  uniq_hosts=`cat "$all_hosts" | sort | uniq`
-  count_uniq_hosts=`cat "$all_hosts" | sort | uniq | wc -l`
+  uniq_hosts=`cat "$f_results" | sort | uniq`
+  count_uniq_hosts=`cat "$f_results" | sort | uniq | wc -l`
   echo "Found $count_uniq_hosts after scraping $page pages."
   echo
 
   if [[ $DEBUG == 0 ]]; then
-    rm -f "$all_hosts"
+    rm -f "$f_results"
   fi
 
   if [[ $OUTPUT_IP == 1 ]]; then
@@ -227,7 +227,6 @@ fi
 
 if [[ $QUIET == 0 ]]; then
   clear
-#  banner
 fi
 
 animation="/-\|"
@@ -255,40 +254,40 @@ else
   fi
 fi
 
-all_hosts=`mktemp -p $TMP_DIR -t bing-ip2hosts.tmp.XXXXXX`
+f_results=`mktemp -p $TMP_DIR -t bing-ip2hosts.tmp.XXXXXX`
 
 while true; do
 
   url="https://www.bing.com/search?q=ip%3A$IP+.&qs=n&first=${page}0&FORM=PERE&setlang=$BING_SETLANG&setmkt=$BING_SETMKT"
   urlpath=`echo "$url" | cut -d '/' -f 4-`
-  out=`mktemp -p "$TMP_DIR" -t bing-ip2hosts.tmp.XXXXXX`
 
-  if ! wget --quiet --no-check-certificate --output-document "$out" "$url"; then
+  f_scraped_html=`mktemp -p "$TMP_DIR" -t bing-ip2hosts.tmp.XXXXXX`
+  if ! wget --quiet --no-check-certificate --output-document "$f_scraped_html" "$url"; then
     echo -e "\n${R}wget failed to scrape $url" >&2
     exit 1
   fi
 
-  last_page_check=`egrep -o '<span class="sb_count">[0-9]+-([0-9]+) of (\1) results' $out`
-  results_count=`egrep -o '<span class="sb_count">[^<]+' $out|cut -d '>' -f 2|cut -d ' ' -f 1-3`
-  single_page=`egrep -o '<span class="sb_count">[0-9] results' $out`
-  results_removed=`egrep -o '>Some results have been removed<' $out`
-  page_title=`egrep -o '<title>([^<]+)' $out | cut -d '>' -f 2`
-  results_highlighted_page=`egrep -o "class=\"sb_pagS sb_pagS_bp b_widePag sb_bp\">([0-9]+)" $out | cut -d '>' -f 2`
+  last_page_check=`egrep -o '<span class="sb_count">[0-9]+-([0-9]+) of (\1) results' $f_scraped_html`
+  results_count=`egrep -o '<span class="sb_count">[^<]+' $f_scraped_html|cut -d '>' -f 2|cut -d ' ' -f 1-3`
+  single_page=`egrep -o '<span class="sb_count">[0-9] results' $f_scraped_html`
+  results_removed=`egrep -o '>Some results have been removed<' $f_scraped_html`
+  page_title=`egrep -o '<title>([^<]+)' $f_scraped_html | cut -d '>' -f 2`
+  results_highlighted_page=`egrep -o "class=\"sb_pagS sb_pagS_bp b_widePag sb_bp\">([0-9]+)" $f_scraped_html | cut -d '>' -f 2`
 
   # no captcha support or detection
   # pages will contain "Typing the characters in the picture above helps us ensure that a person, not a program, is performing a search"
 
-  results=`cat "$out"| egrep -o "<h2><a href=\"[^\"]+" $out | cut -d '"' -f 2`
+  results=`cat "$f_scraped_html"| egrep -o "<h2><a href=\"[^\"]+" $f_scraped_html | cut -d '"' -f 2`
 
   if [[ $DISPLAY_URL_PREFIX == 1 ]]; then
     vhosts=`echo "$results" | cut -d '/' -f 1-3 | tr '[:upper:]' '[:lower:]'`
   else
     vhosts=`echo "$results" | cut -d '/' -f 3 | tr '[:upper:]' '[:lower:]'`
   fi
-  echo -e "$vhosts" >> "$all_hosts"
+  echo -e "$vhosts" >> "$f_results"
 
   old_uniq_hosts=$uniq_hosts
-  uniq_hosts=`cat "$all_hosts" | sort | uniq | wc -l`
+  uniq_hosts=`cat "$f_results" | sort | uniq | wc -l`
 
   if [[ "$DEBUG" == 1 ]]; then
     echo
@@ -317,7 +316,12 @@ while true; do
   #  echo -en "[${animation: $(( $page % 4 )) :1}][ $IP | Scraping page $((page + 1)) | Results: $results_count | Found $uniq_hosts ]          "
     display_progress
   fi
-  
+
+  # clean up tmp files
+  if [[ $DEBUG == 0 ]]; then
+    rm -f "$f_scraped_html"
+  fi
+
   # check end conditions
   if [[ ! -z "$last_page_check" ]]; then
     if [[ $QUIET == 0 ]]; then
@@ -346,11 +350,6 @@ while true; do
     fi
 
     break
-  fi
-
-  # clean up tmp files
-  if [[ $DEBUG == 0 ]]; then
-    rm -f "$out"
   fi
 
   let page=$page+1
