Constants and Environment Variable Names separated with underscores

diff --git a/bing-ip2hosts b/bing-ip2hosts
--- a/bing-ip2hosts
+++ b/bing-ip2hosts
@@ -22,14 +22,14 @@
 
 
 VERSION=0.6
-TMPDIR=/tmp
+TMP_DIR=/tmp
 QUIET=0
-OUTPUTIP=0
-HTTPPREFIX=0
+OUTPUT_IP=0
+HTTP_PREFIX=0
 IP=
 PREFIX=
 DEBUG=0
-STOPAFTERPAGES=5
+STOP_AFTER_PAGES=5
 LANG=en-us
 
 trap ctrl_c INT
@@ -95,11 +95,11 @@ function show_hosts() {
     rm -f "$all_hosts"
   fi
 
-  if [[ $OUTPUTIP == 1 ]]; then
+  if [[ $OUTPUT_IP == 1 ]]; then
     PREFIX="$IP,"
   fi
 
-  if [[ $HTTPPREFIX == 1 ]]; then
+  if [[ $HTTP_PREFIX == 1 ]]; then
     PREFIX="$PREFIX""http://"
   fi
 
@@ -108,7 +108,7 @@ function show_hosts() {
     echo "$PREFIX$h"
   done
 
-  if [[ ! -z "$OUTPUTFILE" ]]; then
+  if [[ ! -z "$OUTPUT_FILE" ]]; then
     for h in `echo "$uniq_hosts"`
     do
       echo "$PREFIX$h" >> "$OUTPUTFILE"
@@ -142,12 +142,12 @@ fi
 
 while getopts "o:m:qt:ip" optionName; do
   case "$optionName" in
-    o) OUTPUTFILE=$OPTARG;;
-    m) STOPAFTERPAGES=$OPTARG;;
+    o) OUTPUT_FILE=$OPTARG;;
+    m) STOP_AFTER_PAGES=$OPTARG;;
     q) QUIET=1;;
-    t) TMPDIR="$OPTARG";;
-    i) OUTPUTIP=1;;
-    p) HTTPPREFIX=1;;
+    t) TMP_DIR="$OPTARG";;
+    i) OUTPUT_IP=1;;
+    p) HTTP_PREFIX=1;;
 [?]) echo "Error"; exit 1;;
 esac
 done
@@ -160,23 +160,23 @@ if [[ -z "$1" ]]; then
 fi
 
 # initialize outputfile
-if [[ ! -z "$OUTPUTFILE" ]]; then
-  touch "$OUTPUTFILE"
-  if [[ ! -w "$OUTPUTFILE" ]]; then
-    echo "Cannot write to $OUTPUTFILE." >&2
+if [[ ! -z "$OUTPUT_FILE" ]]; then
+  touch "$OUTPUT_FILE"
+  if [[ ! -w "$OUTPUT_FILE" ]]; then
+    echo "Cannot write to $OUTPUT_FILE." >&2
     exit 1
   fi
 fi
 
-# Create TMPDIR if necessary
-if [[ ! -d "$TMPDIR" ]]; then
+# Create TMP_DIR if necessary
+if [[ ! -d "$TMP_DIR" ]]; then
   if [[ "$QUIET" = 0 ]]; then
-    mkdir -v -p "$TMPDIR"
+    mkdir -v -p "$TMP_DIR"
   else
-    mkdir -p "$TMPDIR"
+    mkdir -p "$TMP_DIR"
   fi
   if [[ ! "$?" = 0 ]]; then
-    echo "Invalid TMP Directory: $TMPDIR." >&2
+    echo "Invalid TMP Directory: $TMP_DIR." >&2
     exit 1
   fi
 fi
@@ -195,8 +195,8 @@ single_page=
 results_removed=
 declare -a scrape_results
 
-stopsequence="0"
-for ((i = 0; i < (($STOPAFTERPAGES-1)); i++)); do stopsequence+=" 0"; done
+stop_sequence="0"
+for ((i = 0; i < (($STOP_AFTER_PAGES-1)); i++)); do stop_sequence+=" 0"; done
 
 # if the parameter looks like an IP go ahead, otherwise resolve it
 if [[ `echo "$1" | egrep  "(([0-9]+\.){3}[0-9]+)|\[[a-f0-9:]+\]"`  ]]; then
@@ -211,7 +211,7 @@ else
   fi
 fi
 
-all_hosts=`mktemp -p $TMPDIR -t bing-ip2hosts.tmp.XXXXXX`
+all_hosts=`mktemp -p $TMP_DIR -t bing-ip2hosts.tmp.XXXXXX`
 
 while [[ -z "$last_page_check" ]] && [[ -n "$results_count" ]] && [[ -z "$single_page" ]]; do
 
@@ -221,7 +221,7 @@ while [[ -z "$last_page_check" ]] && [[ -n "$results_count" ]] && [[ -z "$single
   fi
 
   url="https://www.bing.com/search?q=ip%3A$IP+.&qs=n&first=${page}0&FORM=PERE&setlang=$LANG"
-  out=`mktemp -p "$TMPDIR" -t bing-ip2hosts.tmp.XXXXXX`
+  out=`mktemp -p "$TMP_DIR" -t bing-ip2hosts.tmp.XXXXXX`
 
   wget --quiet --no-check-certificate --output-document "$out" "$url"
 
@@ -261,7 +261,7 @@ while [[ -z "$last_page_check" ]] && [[ -n "$results_count" ]] && [[ -z "$single
   scrape_results+=($new_results)
 
   if [[ ${scrape_results[@]} =~ $stopsequence ]]; then
-    echo -e "\n$RStopping after $STOPAFTERPAGES without new results.$N" >&2
+    echo -e "\n$RStopping after $STOP_AFTER_PAGES without new results.$N" >&2
     break
   fi
 
